name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar o Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Instalar Dependências do Maven
        run: mvn clean install -DskipTests

      - name: Executar Testes Automatizados
        run: mvn test

      - name: Gerar Relatórios Allure
        run: mvn allure:report

      - name: Publicar Relatórios Allure como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven/index.html