name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar o Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Instalar Google Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Chrome version: $CHROME_VERSION"

      - name: Configurar Variáveis de Ambiente
        run: echo "CI=true" >> $GITHUB_ENV

      - name: Matar processos antigos do Chrome
        run: pkill -9 chrome || true

      - name: Instalar Dependências do Maven
        run: mvn clean install -DskipTests

      - name: Executar Testes Automatizados
        run: mvn test

      - name: Gerar Relatórios Allure
        run: mvn allure:report

      - name: Compactar Relatório Allure
        run: |
          zip -r allure-report.zip target/site/allure-maven/

      - name: Publicar Relatórios Allure como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report.zip